version: "3.9"

services:
  scraper_db:
    image: postgres
    restart: always
    container_name: scraper_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scraped  
    ports:
      - "5432:5432"